steps:
  # Step 1: npm install
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']

  # Step 2: npm build
  - name: 'node:20-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Step 3: docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/global-conflicts-athena-service:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/global-conflicts-athena-service:latest'
      - '-f'
      - 'Dockerfile.prod'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/global-conflicts-athena-service:latest'
  - 'gcr.io/$PROJECT_ID/global-conflicts-athena-service:$BUILD_ID'

timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'
